# SPDX-License-Identifier: GPL-2.0

# Minimal System
obj-y += clk/
obj-y += pinctrl/
obj-y += uart/
obj-y += timer/

# Basic System
obj-y += dma/
obj-y += rtc/
obj-y += bus/
obj-y += dumpreg/
obj-y += iommu/

# Storage
obj-y += mmc/
obj-y += ufs/
obj-y += mtd/
obj-y += redeposit/

# Graphics
obj-y += g2d/
obj-y += di/
obj-y += vin/
obj-y += vfe/
obj-y += drm/

# Multi-Media
obj-y += ve/

# Audio
obj-y += sound/

# Security
obj-y += ce/
obj-y += smc/
obj-y += sid/
obj-y += drm_heap/

# I/O Connectivity
obj-y += pcie/
obj-y += phy/
obj-y += gmac/
obj-y += stmmac/
obj-y += usb/
obj-y += twi/
obj-y += spi-ng/
obj-y += pwm/
obj-y += input/

# Wireless
obj-y += net/

# Power Management
obj-y += irqchip/
obj-y += standby/
obj-y += thermal/
obj-y += nvmem/
obj-y += pm_domain/
obj-y += power/
obj-y += cpufreq/
obj-y += devfreq/

# Misc
obj-y += misc/
