#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-2.0
#
# Synchronize the in-tree bsp/ directory (and the kernel files derived from it)
# with the latest allwinner-bsp sources.
#
# This is meant to be run from the root of the linux git repository, either
# manually or via .github/workflows/sync-bsp.yml.
#
# The generated files below are re-created from the bsp tree:
#   - bsp/                          -> full allwinner-bsp checkout
#   - bsp/include/sunxi-autogen.h   -> version stamp of the fetched bsp commit
#   - arch/arm64/boot/dts/allwinner/*.dts*  (board dts + SoC dtsi)
#   - include/dt-bindings/          -> bsp dt-bindings (merged over mainline)
#   - arch/arm64/configs/bsp.config -> bsp defconfig
#
# Patches that allwinner-bsp ships under bsp/patches/ are NOT applied here;
# Armbian applies its own copies during the kernel build.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

BSP_SOURCE="${BSP_SOURCE:-https://github.com/QinCai-rui/allwinner-bsp.git}"
BSP_BRANCH="${BSP_BRANCH:-linux-6.18.y}"
BSP_CONFIG_DIR="configs/linux-6.18"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo ">>> Fetching allwinner-bsp (${BSP_BRANCH}) from ${BSP_SOURCE}"
git clone --quiet --filter=blob:none --no-checkout "${BSP_SOURCE}" "${WORK_DIR}/bsp-upstream"
git -C "${WORK_DIR}/bsp-upstream" checkout --quiet "${BSP_BRANCH}"

BSP_HASH="$(git -C "${WORK_DIR}/bsp-upstream" rev-parse --short=10 HEAD)"
BSP_TREE="${WORK_DIR}/bsp-upstream"
echo ">>> allwinner-bsp ${BSP_BRANCH} @ ${BSP_HASH}"

if [[ ! -d "${BSP_TREE}/drivers" || ! -d "${BSP_TREE}/${BSP_CONFIG_DIR}" ]]; then
	echo "ERROR: unexpected allwinner-bsp layout on ${BSP_BRANCH}" >&2
	exit 1
fi

# 1. Replace bsp/ with the fetched tree (sunxi-autogen.h is regenerated below).
rsync -a --delete --exclude .git "${BSP_TREE}/" bsp/

# 2. Board device trees + SoC dtsi includes.
cp -f "${BSP_TREE}/${BSP_CONFIG_DIR}"/*.dts* arch/arm64/boot/dts/allwinner/

# 3. dt-bindings shipped with the bsp (merged over mainline headers).
rsync -a "${BSP_TREE}/include/dt-bindings/" include/dt-bindings/

# 4. bsp defconfig used as KBUILD_DEFCONFIG / standalone build entry point.
cp -f "${BSP_TREE}/${BSP_CONFIG_DIR}/defconfig" arch/arm64/configs/bsp.config

# 5. Version stamp. It is gitignored by bsp/.gitignore (upstream treats it as
#    generated) but the BSP clock driver includes <sunxi-autogen.h>, so the file
#    must always exist. Content is derived solely from the bsp commit (hash +
#    commit date), keeping repeated runs with no upstream change idempotent.
BSP_DATE="$(git -C "${BSP_TREE}" log -1 --format='%cs')"
printf '#define AW_BSP_VERSION "%s, %s, RadxaOS SDK"\n' \
	"${BSP_HASH}" "${BSP_DATE}" > bsp/include/sunxi-autogen.h
echo ">>> sunxi-autogen.h -> ${BSP_HASH}"

if git diff --quiet && git diff --cached --quiet; then
	echo ">>> bsp is up to date (${BSP_HASH}); nothing to commit"
	exit 0
fi

# -f: sunxi-autogen.h is matched by bsp/.gitignore but must be tracked so the
#     version stamp ships with the repository.
git add -f bsp/include/sunxi-autogen.h
git add bsp/ arch/arm64/boot/dts/allwinner/*.dts* include/dt-bindings/ arch/arm64/configs/bsp.config
git commit -s -m "bsp: sync from allwinner-bsp @ ${BSP_HASH}

Update the in-tree Allwinner BSP from
${BSP_SOURCE} branch ${BSP_BRANCH}.

Generated by scripts/sync-bsp.sh." > /dev/null

NEW_HEAD="$(git rev-parse HEAD)"
echo ">>> committed ${NEW_HEAD}"
if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
	git push origin "HEAD:${GITHUB_REF_NAME:-linux-6.18.y}"
	echo ">>> pushed to ${GITHUB_REF_NAME:-linux-6.18.y}"
fi
